### ISSUE TITLE
Can not get any data from neo-m9n.

### ISSUE THREAD

**Issue by DandrewsDev** [SimpleMethod/STM32-GNSS#1]
I've tried a hundred or so different things to try and get data from my neo-m9n over uart and am getting nothing. 
Every call to GNSS_GetUniqID returns Unique ID: 0000 0000 0000 0000
I've check my baud rates, and tried values from 9600 to 38400. 
I've made sure my DMA and NVIC settings match whats in the readme. I've checked that Im using the correct pins for rx and tx, and have swapped them rx->tx tx->rx and then rx->rx tx->tx a few times. 
The D-Sel pin is left unattached, tho I have also pulled it to 3.3v to ensure that it was using the UART interface.
The neo-m9n module works perfectly with a PC over USB. 

Code Im using to 
`    GNSS_Init(&GNSS_Handle, sensorHub.huart1);
    HAL_Delay(1000);
    GNSS_LoadConfig(&GNSS_Handle);
    GNSS_GetUniqID(&GNSS_Handle);
    char accDataOut[64];
    memset(accDataOut, 0, 64);
    sprintf(accDataOut, "Unique ID: %04X %04X %04X %04X \n\r",
           GNSS_Handle.uniqueID[0], GNSS_Handle.uniqueID[1],
           GNSS_Handle.uniqueID[2], GNSS_Handle.uniqueID[3]);
    CDC_Transmit_FS((uint8_t *) accDataOut, strlen(accDataOut));`
    
Where sensorHub.huart1 is set in my main.c 
`UART_HandleTypeDef huart1;`
after `MX_USART1_UART_Init();` is called.
Is there anything you would suggest I try, or any steps I could take to further debug what might be happening? 

As far as I can tell, the HAL_UART_Receive_DMA and HAL_UART_Receive_IT calls in GNSS.c are never getting any data.

**Comment by Rob-le-Houe** [comment]
did you find a solution to this? I have similar problem with M8T. The device ID constantly changes and I occasionally get some usable data but most of the time it receives nothing. Boots and outputs data in seconds over USB.
